//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infocus.Edi.Bone.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infocus.Edi.Bone.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;&lt;Application&gt;&lt;forms&gt;&lt;action type=&quot;add&quot;&gt;&lt;form appformnumber=&quot;InfoW2IStatus&quot; FormType=&quot;InfoW2IStatus&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;InfoW2IStatus&quot; title=&quot;Infocus EDI - 850 Import Status&quot; visible=&quot;0&quot; default_button=&quot;BtOk&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;540&quot; top=&quot;196&quot; width=&quot;356&quot; height=&quot;179&quot; client_width=&quot;340&quot; client_height=&quot;140&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot; modality=&quot;0&quot;&gt;&lt;datasources&gt;&lt;dbdatasources&gt;&lt;action type=&quot;add&quot;/&gt;&lt;/dbdatasources&gt;&lt;userdatasour [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Import850StatusForm {
            get {
                return ResourceManager.GetString("Import850StatusForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;InfoW2940Status&quot; FormType=&quot;InfoW2940Status&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;InfoW2940Status&quot; title=&quot;Infocus EDI - 940 Import Status&quot; visible=&quot;0&quot; default_button=&quot;BtOk&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;540&quot; top=&quot;196&quot; width=&quot;356&quot; height=&quot;179&quot; client_width=&quot;340&quot; client_height=&quot;140&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot; modality=&quot;0&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;dbdatasources&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Import940StatusForm {
            get {
                return ResourceManager.GetString("Import940StatusForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;&lt;Application&gt;&lt;forms&gt;&lt;action type=&quot;add&quot;&gt;&lt;form appformnumber=&quot;InfoW2180&quot; FormType=&quot;InfoW2180&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;InfoW2180&quot; title=&quot;Infocus EDI - Process 180&quot; visible=&quot;0&quot; default_button=&quot;BtOk&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;542&quot; top=&quot;196&quot; width=&quot;345&quot; height=&quot;199&quot; client_width=&quot;329&quot; client_height=&quot;160&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot; modality=&quot;0&quot;&gt;&lt;datasources&gt;&lt;dbdatasources&gt;&lt;action type=&quot;add&quot;/&gt;&lt;/dbdatasources&gt;&lt;userdatasources&gt;&lt;action type=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Process180Form {
            get {
                return ResourceManager.GetString("Process180Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;InfoW2940&quot; FormType=&quot;InfoW2940&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;InfoW2940&quot; title=&quot;Infocus EDI - Process 940&quot; visible=&quot;0&quot; default_button=&quot;BtOk&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;542&quot; top=&quot;196&quot; width=&quot;345&quot; height=&quot;180&quot; client_width=&quot;473&quot; client_height=&quot;254&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Process940Form {
            get {
                return ResourceManager.GetString("Process940Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;InfoW2Pro&quot; FormType=&quot;InfoW2Pro&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;InfoW2Pro&quot; title=&quot;Infocus EDI - Process 850&quot; visible=&quot;0&quot; default_button=&quot;BtOk&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;542&quot; top=&quot;196&quot; width=&quot;345&quot; height=&quot;180&quot; client_width=&quot;473&quot; client_height=&quot;254&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProcessEdiForm {
            get {
                return ResourceManager.GetString("ProcessEdiForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;InfoW2R850&quot; FormType=&quot;InfoW2R850&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;InfoW2R850&quot; title=&quot;Reject Unprocessed 850&quot; visible=&quot;1&quot; default_button=&quot;BtOk&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;88&quot; width=&quot;845&quot; height=&quot;587&quot; client_width=&quot;829&quot; client_height=&quot;548&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; modality=&quot;0&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot;/&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Reject850Form {
            get {
                return ResourceManager.GetString("Reject850Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;&lt;Application&gt;&lt;forms&gt;&lt;action type=&quot;add&quot;&gt;&lt;form appformnumber=&quot;InfoW2R810&quot; FormType=&quot;InfoW2R810&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;InfoW2R810&quot; title=&quot;Select Orders to Resend 810&quot; visible=&quot;1&quot; default_button=&quot;BtOk&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;434&quot; top=&quot;45&quot; width=&quot;577&quot; height=&quot;634&quot; client_width=&quot;561&quot; client_height=&quot;595&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; modality=&quot;0&quot;&gt;&lt;datasources&gt;&lt;dbdatasources&gt;&lt;action type=&quot;add&quot;&gt;&lt;datasource tablename=&quot;ODLN&quot;/&gt;&lt;/action&gt;&lt;/dbdatasource [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Resend810Form {
            get {
                return ResourceManager.GetString("Resend810Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;InfoW2R856&quot; FormType=&quot;InfoW2R856&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;InfoW2R856&quot; title=&quot;Select Orders to Resend 856&quot; visible=&quot;1&quot; default_button=&quot;BtOk&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;88&quot; width=&quot;551&quot; height=&quot;587&quot; client_width=&quot;535&quot; client_height=&quot;548&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; modality=&quot;0&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;ad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Resend856Form {
            get {
                return ResourceManager.GetString("Resend856Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;&lt;Application&gt;&lt;forms&gt;&lt;action type=&quot;add&quot;&gt;&lt;form appformnumber=&quot;InfoW2Sel&quot; FormType=&quot;InfoW2Sel&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;InfoW2Sel&quot; title=&quot;Selection Criteria&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;88&quot; width=&quot;391&quot; height=&quot;339&quot; client_width=&quot;375&quot; client_height=&quot;300&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; modality=&quot;0&quot;&gt;&lt;datasources&gt;&lt;dbdatasources&gt;&lt;action type=&quot;add&quot;/&gt;&lt;/dbdatasources&gt;&lt;userdatasources&gt;&lt;action type=&quot;add&quot;/&gt;&lt;/userdatasourc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResendSelForm {
            get {
                return ResourceManager.GetString("ResendSelForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot; ?&gt;&lt;Application&gt;&lt;forms&gt;&lt;action type=&quot;add&quot;&gt;&lt;form appformnumber=&quot;InfoW2Set&quot; FormType=&quot;InfoW2Set&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;InfoW2Set&quot; title=&quot;Infocus EDI - Settings&quot; visible=&quot;0&quot; default_button=&quot;BtOk&quot; pane=&quot;0&quot; color=&quot;0&quot; left=&quot;542&quot; top=&quot;196&quot; width=&quot;461&quot; height=&quot;289&quot; client_width=&quot;445&quot; client_height=&quot;250&quot; AutoManaged=&quot;0&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;1&quot; modality=&quot;0&quot;&gt;&lt;datasources&gt;&lt;dbdatasources&gt;&lt;action type=&quot;add&quot;/&gt;&lt;/dbdatasources&gt;&lt;userdatasources&gt;&lt;action type=&quot;add [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsForm {
            get {
                return ResourceManager.GetString("SettingsForm", resourceCulture);
            }
        }
    }
}
