//****************************************************************************
//
//  File:      BoneItem.cs
//
//  Copyright (c) SAP 
//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
//****************************************************************************
using System;

namespace Infocus.Framework.SapBone
{
  /// <summary>
  /// Base class for the events management on an item entity.
  /// </summary>
  /// <remarks>
  /// In your project you will have a class inheriting from BoneItem
  /// for each item you want to handle one/several events.
  /// <para>The name of the inherited class will be formated as following: Itype_Ftype_Iuid</para>
  /// <para>  Where Itype: Type of the item (Button, Folder, Matrix,...)</para>
  /// <para>        Ftype:  Form type of the form where the item is included.</para>
  /// <para>        Iuid:  Unique ID of the item.</para>
  /// <para> The inherited class will contain  a basic constructor plus one function per each
  /// listener added for the item.</para>
  /// 
  /// </remarks>
  /// <example>
  /// This example shows the autogenerated class representing an item of type 
  /// Button with UID="But1" inside a form of type CustForm.
  /// <para>This item has the autogenerated code of a listener receiving the ItemEvent et_ITEM_PRESSED</para>
  /// <code lang="Visual Basic" escaped="true">
  /// Public Class Button__CustForm__But1
  ///   Inherits BoneItem
  /// 
  ///   Public Sub New()
  ///     MyBase.New
  ///     FormType = "CustForm"
  ///     ItemUID = "But1";
  ///   End Sub
  ///       
  ///   BoneListener(BoEventTypes.et_ITEM_PRESSED, false)  _
  ///   Public Overridable Function OnBeforeItemPressed(ByVal pVal As ItemEvent) As Boolean
  ///     Dim form As Form = BoneConnectionContext.Application.Forms.Item(pVal.FormUID)
  ///     Dim item As Item = form.Items.Item("But1")
  ///     Dim but As Button = ((Button)(item.Specific))
  ///     'ADD YOUR ACTION CODE HERE ...
  ///     Return true
  ///   End Function
  /// End Class
  /// </code>
  /// <code lang="C#" escaped="true">
  /// public class Button__CustForm__But1 : BoneItem {
  ///       
  ///   public Button__CustForm__But1() 
  ///   {
  ///     FormType = "CustForm";
  ///     ItemUID = "But1";
  ///   }
  ///       
  ///   [BoneListener(BoEventTypes.et_ITEM_PRESSED, true)]
  ///   public virtual bool OnBeforeItemPressed(ItemEvent pVal) 
  ///   {
  ///     Form form = BoneConnectionContext.Application.Forms.Item(pVal.FormUID);
  ///     Item item = form.Items.Item("But1");
  ///     Button but = ((Button)(item.Specific));
  ///     // ADD YOUR ACTION CODE HERE ...
  ///   }
  /// }
  /// </code>
  /// </example>
  public abstract class BoneItem : BoneAction
  {
    /// <summary>
    /// String specifying the form type.
    /// </summary>
    protected string FormType = "";
    /// <summary>
    /// String specifying the item Unique ID.
    /// </summary>
    protected string ItemUID = "";

    /////////////////////////////////////////////////////////////////////////////////

    /// <summary>
    /// Empty Constructor.
    /// </summary>
    protected BoneItem()
    {
    }

    /// <summary>
    /// Returns the key identifying the item entity for the events management.
    /// </summary>
    /// <param name="before">Boolean value specifying whether the action
    /// wants to handle the before or the after notification.</param>
    /// <returns>String identifying the action key.</returns>
    public override sealed string GetKey(bool before)
    {
      return EventTables.GetActionKey(FormType, ItemUID, before);
    }
  }
}

