//****************************************************************************
//
//  File:      BoneForm.cs
//
//  Copyright (c) SAP 
//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
//****************************************************************************
using System;

namespace Infocus.Framework.SapBone
{
  /// <summary>
  /// Base class for the events management on a form entity.
  /// </summary>
  /// <remarks>
  /// In your AddOn autogenerated project you will have a class inheriting 
  /// from BoneForm for each form you want to handle one/several events.
  /// <para>The name of the inherited class will be formated as following: Form_FType </para>
  /// <para>  Where FType is the form type. </para>
  /// <para>The inherited class will contain  a basic constructor plus one function per each
  /// listener added for the form.</para>
  /// </remarks>
  /// <example>
  /// This example shows the autogenerated class representing a form of type CustForm.
  /// <para>This form has the autogenerated code of a listener receiving the ItemEvent et_FORM_LOAD</para>
  /// <code lang="Visual Basic" escaped="true">
  /// Public Class Form__CustForm
  ///   Inherits BoneForm
  /// 
  ///   Public Sub New()
  ///     MyBase.New
  ///     FormType = "CustForm"
  ///   End Sub
  ///       
  ///   BoneListener(BoEventTypes.et_FORM_LOAD, false)
  ///   Public Overridable Function OnFormLoad(ByVal pVal As ItemEvent) As Boolean
  ///     Dim form As Form = BoneConnectionContext.Application.Forms.Item(pVal.FormUID)
  ///     'ADD YOUR ACTION CODE HERE ...
  ///     Return true
  ///   End Function
  /// End Class
  /// </code>
  /// <code lang="C#" escaped="true">
  /// public class Form__CustForm : BoneForm {
  ///      
  ///   public Form__CustForm() 
  ///   {
  ///     FormType = "CustForm";
  ///   }
  ///       
  ///   [BoneListener(BoEventTypes.et_FORM_LOAD, false)]
  ///   public virtual bool OnFormLoad(ItemEvent pVal) 
  ///   {
  ///     Form form = BoneConnectionContext.Application.Forms.Item(pVal.FormUID)
  ///     // ADD YOUR ACTION CODE HERE ...
  ///     return true;
  ///   }
  /// }
  /// </code>
  /// </example>
  public abstract class BoneForm : BoneAction
  {
    /// <summary>
    /// String specifying the form type.
    /// </summary>
    protected string FormType ="";

    /////////////////////////////////////////////////////////////////////////////////
		
    /// <summary>
    /// Empty Constructor.
    /// </summary>
    protected BoneForm()
    {
    }

    /// <summary>
    /// Returns the key identifying the form entity for the events management.
    /// </summary>
    /// <param name="before">Boolean value specifying whether the action
    /// wants to handle the before or the after notification.</param>
    /// <returns>String identifying the action key.</returns>
    public override sealed string GetKey(bool before)
    {
      return EventTables.GetActionKey(FormType,"",before);
    }
  }
}
