//****************************************************************************
//
//  File:      B1Menu.cs
//
//  Copyright (c) SAP 
//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
//****************************************************************************
using System;

namespace Infocus.Framework.SapBone
{
  /// <summary>
  /// Base class for the events management on a menu entity.
  /// </summary>
  /// <remarks>
  /// In your project you will have a class inheriting from B1Menu
  /// for each menu you want to handle one/several events.
  /// <para>The name of the inherited class will be formated as following: Menu_Muid </para>
  /// <para>  Where Muid is the Unique ID of the menu. </para>
  /// <para>The inherited class will contain  a basic constructor plus one function per each
  /// listener added for the menu.</para>
  /// </remarks>
  /// <example>
  /// This example shows the autogenerated class representing a form of type CustForm.
  /// <para>This form has the autogenerated code of a listener receiving the ItemEvent et_FORM_LOAD</para>
  /// <code lang="Visual Basic" escaped="true">
  /// Public Class Menu__NS_CustMenu
  ///   Inherits B1Menu
  /// 
  ///   Public Sub New()
  ///     MyBase.New
  ///     MenuUID = "NS_CustMenu"
  ///   End Sub
  ///       
  ///   BoneListener(BoEventTypes.et_MENU_CLICK, false)  _ 
  ///   Public Overridable Function OnBeforeMenuClick(ByVal pVal As MenuEvent) As Boolean
  ///     'ADD YOUR ACTION CODE HERE ...
  ///     Return true
  ///   End Function
  /// End Class
  /// </code>
  /// <code lang="C#" escaped="true">
  /// public class Menu__NS_CustMenu : B1Menu {
  ///      
  ///   public Menu__NS_CustMenu() 
  ///   {
  ///     MenuUID = "NS_CustMenu"
  ///   }
  ///       
  ///   [BoneListener(BoEventTypes.et_MENU_CLICK, false)]
  ///   public virtual bool OnBeforeMenuClick(MenuEvent pVal) 
  ///   {
  ///     // ADD YOUR ACTION CODE HERE ...
  ///     return true;
  ///   }
  /// }
  /// </code>
  /// </example>
  public abstract class BoneMenu : BoneAction
  {
    /// <summary>
    /// Unique ID identifying a Menu.
    /// </summary>
    protected string MenuUID = "";

    /////////////////////////////////////////////////////////////////////////////////

    /// <summary>
    /// Empty Constructor.
    /// </summary>
    protected BoneMenu()
    {
    }

    /// <summary>
    /// Returns the key identifying the menu entity for the events management.
    /// </summary>
    /// <param name="before">Boolean value specifying whether the action
    /// wants to handle the before or the after notification.</param>
    /// <returns>String identifying the action key.</returns>
    public override sealed string GetKey(bool before)
    {
      return EventTables.GetActionKey(MenuUID,before);
    }
  }
}

