; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Test Infocus EDI (x64)"
#define MyAppVersion "2023.10.05.00"
#define MyAppPublisher "Infocus Technologies"
#define MyAppURL "http://www.infocustechnologies.net"
#define MyAppExeName "Infocus.Edi.Bone.Test.exe"
#define MyInstallRegistryRoot "Software\Infocus Technologies"
#define MyInstallRegistryKey "Infocus.Edi.Bone.Test"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{3FB2D42A-31D1-42A4-900D-3B6C0EDFF0C2}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={code:GetDefaultAddOnDir}
DisableDirPage=yes
DisableProgramGroupPage=yes
OutputBaseFilename=Infocus.Edi.Bone.Install.Test.x64
SetupIconFile=C:\Infocus Source\Infocus.WebApi\Infocus.Edi.Bone\Images\swirl-32x32.ico
UninstallDisplayIcon=C:\Infocus Source\Infocus.WebApi\Infocus.Edi.Bone\Images\swirl-32x32.ico
Compression=lzma
SolidCompression=yes
UsePreviousAppDir=no
AppendDefaultDirName=yes
VersionInfoProductVersion={#MyAppVersion}
VersionInfoVersion={#MyAppVersion}
ArchitecturesInstallIn64BitMode=x64

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "libs\AddOnInstallAPI.dll"; Flags: dontcopy;
;Source: "C:\Users\Joel\Documents\Visual Studio 2015\Projects\Infocus.WebApi\Infocus.Edi.Bone\bin\x64\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Infocus Source\Infocus.WebApi\Infocus.Edi.Bone\bin\x64\Debug\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKLM64; Subkey: "{#MyInstallRegistryRoot}"; Flags: uninsdeletekey
Root: HKLM64; Subkey: "{#MyInstallRegistryRoot}\{#MyInstallRegistryKey}"; Flags: uninsdeletekey
Root: HKLM64; Subkey: "{#MyInstallRegistryRoot}\{#MyInstallRegistryKey}"; ValueType: string; ValueName: "InstallPath"; ValueData: "{app}"

[Code]
//-Public Vars
var
  InstallDirectoryPath : string;
  BusinessOneApiPath : string;
  IsUninstall : Boolean;
  FinishedInstall : Boolean;
  IsRunningInBusinessOne : Boolean;

//-External Functions (AddOnInstallAPI.dll)
//function EndInstall: integer; external 'EndInstall@files:AddOnInstallAPI.dll stdcall';
function EndInstallEx(srcPath:string;isSuccess:boolean): integer; external 'EndInstallEx@files:AddOnInstallAPI.dll stdcall';
function EndUninstall(srcPath:string;isSuccess:boolean): integer; external 'EndUninstall@files:AddOnInstallAPI.dll stdcall';
function SetAddOnFolder(srcPath : string): integer; external 'SetAddOnFolder@files:AddOnInstallAPI.dll stdcall';
function RestartNeeded :integer; external 'RestartNeeded@files:AddOnInstallAPI.dll stdcall delayload ';


//-Check if the application is installed;
//- if yes --> suggest to Remove
//- if no --> Install
function Uninstall(): boolean;
  var
    ResultCode: Integer;
  begin
    // MsgBox('Entering Uninstall.', mbInformation, MB_OK);
	  // MsgBox('Current dir is <' + GetCurrentDir + '>', mbInformation, MB_OK);
	// MsgBox(InstallDirectoryPath + '\unins000.exe', mbInformation, MB_OK);
	//Exec(GetCurrentDir + '\unins000.exe', '', '', SW_SHOW, ewWaitUntilTerminated, ResultCode);
    if RegQueryStringValue(HKLM64, '{#MyInstallRegistryRoot}\{#MyInstallRegistryKey}', 'InstallPath', InstallDirectoryPath) then 
    begin
      Exec(InstallDirectoryPath + '\unins000.exe', '', '', SW_SHOW, ewWaitUntilTerminated, ResultCode);
      EndUninstall(InstallDirectoryPath, True);
      //MsgBox('{#MyAppName} was successfully removed.', mbInformation, MB_OK);
      result := True;
    end
    else
    begin
      MsgBox('Could not obtain RegistryKey value for HKLM64\{#MyInstallRegistryRoot}\{#MyInstallRegistryKey}\InstallPath.  Aborting Uninstall.', mbInformation, MB_OK);
      EndUninstall('', False);
      result := False;
    end
  end;

//function IsRunningInBusinessOne() : Boolean;
//begin
//  MsgBox('Entering IsRunningInBusiness One. GetCmdTail = ' + GetCmdTail, mbInformation, MB_OK);
//  if Pos('$$B1ADDONINSTALL$$', GetCmdTail) <> 0 then
//  begin
//   result := True;
//  end
//  else
//  begin
//    result := False;
//  end
//end;

function GetDefaultAddOnDir(Param : string): string;
begin
  //-Default Directory to Install the Add-On
     result := InstallDirectoryPath;
end;

//-When Setup starts, get the parameters of B1
function ParseCommandLineArguments() : Boolean;
  var
    commandLineArgs : string;
    positionOfToken : Integer;
  begin
    //MsgBox('Entering ParseCommandLineArguments', mbInformation, MB_OK);
    //-First Check if the application is installed
    //MsgBox('JBB  :' + GetCmdTail, mbInformation, MB_OK)
    //MsgBox('JBB# :' + IntToStr(ParamCount), mbInformation, MB_OK)
    //commandLineArgs := GetCmdTail;
    if ParamCount > 1 then
    begin
      if IsRunningInBusinessOne then
      begin
        commandLineArgs := ParamStr(ParamCount);       		
        if pos('/uninstall', GetCmdTail) <> 0 then
        begin
          //MsgBox('IsUninstall = true.', mbInformation, MB_OK);
          IsUninstall := True;
        end
        else
        begin
          //MsgBox('IsUninstall = false.', mbInformation, MB_OK);
          IsUninstall := False;		
          StringChangeEx(commandLineArgs, '/z', '', True);
          StringChangeEx(commandLineArgs, '"', '', True); 
          commandLineArgs := Trim(commandLineArgs);
          positionOfToken := Pos('|', commandLineArgs);
          InstallDirectoryPath := Copy(commandLineArgs, 1, positionOfToken - 1);
          BusinessOneApiPath := Copy(commandLineArgs, positionOfToken + 1, 9999999);
        end
        result := True;
      end
      else
      begin
        MsgBox('This installer must be invoked by SAP Business One (10).', mbInformation, MB_OK);
        result := False;
      end
    end
    else
    begin
      IsRunningInBusinessOne := False;
      MsgBox('This installer must be invoked by SAP Business One (11).', mbInformation, MB_OK);
      result := False;
    end
  end;

function InitializeSetup(): Boolean;
  begin 
  //MsgBox('Entering InitializeSetup. ' + GetCmdTail, mbInformation, MB_OK);
    if Pos('$$B1ADDONINSTALL$$', GetCmdTail) <> 0 then
    begin
      IsRunningInBusinessOne := True;
      if ParseCommandLineArguments then
      begin
        if IsUninstall then
          begin
            Uninstall;
            result := False;
          end
        else
          begin
            result := True;
          end
      end
      else
        begin                     
          EndInstallEx('', False);
          result := False;                                                  
        end
    end
    else
    begin
      IsRunningInBusinessOne := False;
      MsgBox('This installer must be invoked by SAP Business One (13).', mbInformation, MB_OK);
      result := False;
    end
  end;

//function InitializeUninstall() : Boolean;
//begin
//  MsgBox('Entering InitializeUninstall. ' + GetCmdTail, mbInformation, MB_OK);
//  if Pos('$$B1ADDONINSTALL$$', GetCmdTail) <> 0 then
//  begin
//    IsRunningInBusinessOne := True;
//  end
//  else
//  begin
//  IsRunningInBusinessOne := False;
//    MsgBox('This installer must be invoked by SAP Business One (12).', mbInformation, MB_OK);
//    EndUninstall('', False);
//    result := False;
//  end
//end;

function NextButtonClick(CurPageID: Integer): Boolean;
  begin
    Result := True;
    case CurPageID of
      //wpSelectDir :
        //begin
          //AddOnDir := ExpandConstant('{app}');
          //end;
      wpFinished :
        begin
          //-If All OK then
          if FinishedInstall then
            begin
              //-Send to B1 the Installation Folder and ...
              SetAddOnFolder( ExpandConstant('{app}'));
              //-...indicates finish installing
              //MsgBox('Preparing To Call EndInstallEx', mbInformation, MB_OK);
             EndInstallEx(InstallDirectoryPath, True);
            end;
        end;
    end;
  end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
    FinishedInstall := True;
end;

function UninstallNeedRestart(): Boolean;
begin
  //EndUninstall('', True);
  Result := False;
end;

