CREATE TABLE  [dbo].[InfocusEdi850HeaderRecord](
	[HeaderId] [int] IDENTITY(1,1) NOT NULL,
	[RecordDate] [datetime] NULL,
	[Processed] [bit] NOT NULL,
	[Processed856] [bit] NOT NULL,
	[Processed810] [bit] NOT NULL,
	[ErrorMessage] [nvarchar](max) NULL,
	[SalesOrderKey] [int] NULL,
	[ReceivedDateTime] [datetime] NOT NULL,
	[ProcessedDateTime] [datetime] NULL,
	[Processed856DateTime] [datetime] NULL,
	[Processed810DateTime] [datetime] NULL,
	[CardCode] [nvarchar](30) NULL,
	[PurchaseOrderReference] [nvarchar](100) NULL,
	[PurchaseOrderDate] [datetime] NULL,
	[Department] [nvarchar](100) NULL,
	[VendorNumber] [nvarchar](100) NULL,
	[ReplenishmentNumber] [nvarchar](100) NULL,
	[BuyerName] [nvarchar](255) NULL,
	[DeliveryPhoneNumber] [nvarchar](100) NULL,
	[TruckLoadNumber] [nvarchar](120) NULL,
	[CarrierCode] [nvarchar](100) NULL,
	[ConditionDescription] [nvarchar](max) NULL,
	[ShipToName] [nvarchar](255) NULL,
	[ShipToAttention] [nvarchar](255) NULL,
  	[ShipToLocationCode] [nvarchar](100) NULL,
    [ShipToStoreLocation] [nvarchar](100) NULL,	
	[ShipToAddress1] [nvarchar](100) NULL,
	[ShipToAddress2] [nvarchar](100) NULL,
	[ShipToCity] [nvarchar](100) NULL,
	[ShipToState] [nvarchar](3) NULL,
	[ShipToZip] [nvarchar](20) NULL,
	[ShipToCountry] [nvarchar](100) NULL,
	[PaymentMethod] [nvarchar](100) NULL,
	[PromotionChargeCode] nvarchar(100) NULL,
	[RequestedDeliveryDate] [datetime] NULL,
	[RequestedShipDate] [datetime] NULL,
	[UserDefined01] [nvarchar](max) NULL,
	[UserDefined02] [nvarchar](max) NULL,
	[UserDefined03] [nvarchar](max) NULL,
	[UserDefined04] [nvarchar](max) NULL,
	[UserDefined05] [nvarchar](max) NULL,
	[UserDefined06] [nvarchar](max) NULL,
	[UserDefined07] [nvarchar](max) NULL,
	[UserDefined08] [nvarchar](max) NULL,
	[UserDefined09] [nvarchar](max) NULL,
	[UserDefined10] [nvarchar](max) NULL,
	[ShipToStoreLocation] [nvarchar](100) NULL,
	[Processed870] [bit] NULL,
	[Processed870DateTime] [datetime] NULL,
	[Last870Status] [nchar](2) NULL,
	[Processed860] [bit] NULL,
	[Processed860DateTime] [datetime] NULL,
	[Last860Status] [nchar](2) NULL,	
	[TrxPurpose] [nchar](2) NULL,
	[ReasonCode870] [nchar](10) NULL,
	[OrderType] [nchar](2) NULL,
	[ConfirmationNo] [int] NULL,
	[OrderBuyName] [nvarchar](75) NULL,
	[OrderBuyAddr1] [nvarchar](100) NULL,
	[OrderBuyAddr2] [nvarchar](100) NULL,
	[OrderBuyCity] [nvarchar](100) NULL,
	[OrderBuyState] [nvarchar](3) NULL,
	[OrderBuyZip] [nvarchar](20) NULL,
	[OrderBuyCountryCd] [nvarchar](3) NULL,
	[JobNumber] [nvarchar](30) NULL,
	[ExpectedDeliveryDate] [datetime] NULL,
	[ExpectedShipDate] [datetime] NULL,
	[OrderBuyCode] [nvarchar](100) NULL,
	[ShipmentWeight] [numeric](18, 0) NULL,
	[DocumentType] [nchar](20) NULL,
	[Processed810C] [bit] NULL,
	[Processed810CDateTime] [datetime] NULL,
	[TermsType] [nvarchar](2) NULL,
	[TermsBasisCode] [nvarchar](2) NULL,
	[TermsDiscount] [int] NULL,
	[TermsDiscountDays] [int] NULL,
	[TermsNetDueDate] [date] NULL,
	[TermsNetDays] [int] NULL,
	[TermsDescription] [nvarchar](80) NULL,
	[TermsDayofMonth] [int] NULL,
	[Processed855] [bit] NULL,
	[Processed855DateTime] [datetime] NULL,
	[Last855Status] [nchar](2) NULL,
	[SBOCardCode] [nvarchar](30) NULL,
	[PackingNotes] [nvarchar](max) NULL,
	[BOLNotes] [nvarchar](max) NULL,
	[TransportMethod] [nvarchar](50) NULL,
	[ServiceLevel] [nvarchar](50) NULL,
	[DeliveryContact] [nvarchar](max) NULL,
	[DeliveryEmail] [nvarchar](max) NULL,
	[HandlingCode] [nvarchar](50) NULL,
	[Processed860] [bit] NULL,
	[Processed860DateTime] [datetime] NULL,
	[Last860Status] [nchar](10) NULL,
	[BillToName] [nvarchar](255) NULL,
	[BillToAddress1] [nvarchar](100) NULL,
	[BillToAddress2] [nvarchar](100) NULL,
	[BillToCity] [nvarchar](100) NULL,
	[BillToState] [nvarchar](3) NULL,
	[BillToZip] [nvarchar](20) NULL,
	[BillToCountry] [nvarchar](100) NULL,
	[BillToCode] [nvarchar](100) NULL,
	[InternalControlNo] [nvarchar](30) NULL,
	[ContractNumber] [nvarchar](30) NULL,
	[PriorityShippingFee] [float] NULL,
	[CustomerOrderNumber] [nvarchar](50) NULL,
	[HandlingDescription] [nvarchar](80) NULL,
	[PaymentDescription] [nvarchar](80) NULL,
	[MessageText] [nvarchar](max) NULL,
	[ReferenceId] [nvarchar](50) NULL,
	[BrandName] [nvarchar](80) NULL,
	[AllowanceCode] [nvarchar](4) NULL,
	[AllowanceRate] [float] NULL,
	[ShipAfterDate] [datetime] NULL,
	[ShipCutOffDate] [datetime] NULL,
	[BillToContact] [nvarchar](60) NULL,
	[BillToPhoneNo] [nvarchar](80) NULL,
	[BillToFaxNo] [nvarchar](80) NULL,
	[BillToEmail] [nvarchar](80) NULL,
	[PoolPointId] [nvarchar](60) NULL,
	[PoolPointName] [nvarchar](80) NULL,
	[CrossDockId] [nvarchar](60) NULL,
	[CrossDockName] [nvarchar](80) NULL,
	[DeliveryAgentId] [nvarchar](60) NULL,
	[DeliveryAgentName] [nvarchar](80) NULL,
	[DeliveryFaxNo] [nvarchar](80) NULL,
	[BillingId] [nvarchar](50) NULL,
	[BillingText] [nvarchar](max) NULL,
	[ShippingAccount] [nvarchar](50) NULL,
	[SupplierName] [nvarchar](80) NULL,
	[SupplierFax] [nvarchar](80) NULL,
	[SupplierPhone] [nvarchar](80) NULL,
	[TotalExpectedCost] [float] NULL,
	[TransportRouting] [nvarchar](80) NULL,
	[ShipmentZone] [nvarchar](80) NULL,
	[WebSite] [nvarchar](100) NULL,
	[HasOpen856] [bit] NULL,
	[VendorNote1] [nvarchar](80) NULL,
	[VendorNote2] [nvarchar](80) NULL,
	[Processed753] [bit] NULL,
	[Processed753DateTime] [datetime] NULL,
  	[Last753TrxType] [nvarchar](02) NULL,
		[ConsumerPO] [nvarchar](30) NULL,
	[FreightBillType] [nvarchar](100) NULL,
	[OrderType3PL] [nvarchar](10) NULL,
	[ConsumerPODate] [date] NULL,
	[ShipFromStore] [nvarchar](20) NULL,
	[ShipFromName] [nvarchar](60) NULL,
	[POPurposeCode] [nvarchar](30) NULL,
	[PackingStoreCode] [nvarchar](30) NULL,
	[ReceiptId] [nvarchar](40) NULL,
	[CustCode3PL] [nvarchar](20) NULL,
	[VendorMessage] [nvarchar](250) NULL,
	[OrderMessage] [nvarchar](450) NULL,
	[POType3PL] [nvarchar](3) NULL,
	[DiscountDescr] [nvarchar](60) NULL,
	[GiftMessage] [nvarchar](250) NULL,
	[ItemTaxType] [nvarchar](30) NULL,
	[TaxComponent] [nvarchar](30) NULL,
	[CustomerRef] [nvarchar](100) NULL,
	[ThirdPtyBTName] [nvarchar](60) NULL,
	[ThirdPtyBTAddr] [nvarchar](100) NULL,
	[ThirdPtyBTCity] [nvarchar](60) NULL,
	[ThirdPtyBTState] [nvarchar](10) NULL,
	[ThirdPtyBTZip] [nvarchar](10) NULL,
	[ThirdPtyBTCountry] [nvarchar](4) NULL,
	[BusinessRuleCd] [nvarchar](50) NULL,
	[ShipmentCd] [nvarchar](50) NULL,
	[ThirdPtyAcct] [nvarchar](50) NULL,
	[Shipper3PL] [nvarchar](50) NULL,
	[OrderPriority3PL] [nvarchar](50) NULL,
	[Orig855ProcessedDateTime] [datetime] NULL,
	[Orig856ProcessedDateTime] [datetime] NULL,
	[TrxSource] [nvarchar](10) NULL,
	[IgnoreTrxRequest] [nvarchar](1) NULL,
 CONSTRAINT [PK.InfocusEdi850HeaderRecord] PRIMARY KEY CLUSTERED 
(
	[HeaderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE  [dbo].[InfocusEdi850DetailRecord](
	[DetailId] [int] IDENTITY(1,1) NOT NULL,
	[HeaderId] [int] NOT NULL,
	[LineNumber] [int] NOT NULL,
	[BuyerItemCode] [nvarchar](100) NULL,
	[VendorItemCode] [nvarchar](100) NULL,
	[Quantity] [float] NOT NULL,
	[UnitOfMeasure] [nvarchar](100) NULL,
	[UnitPrice] [float] NULL,
	[ItemDescription] [nvarchar](255) NULL,
	[UserDefined01] [nvarchar](max) NULL,
	[UserDefined02] [nvarchar](max) NULL,
	[UserDefined03] [nvarchar](max) NULL,
	[UserDefined04] [nvarchar](max) NULL,
	[UserDefined05] [nvarchar](max) NULL,
	[UserDefined06] [nvarchar](max) NULL,
	[UserDefined07] [nvarchar](max) NULL,
	[UserDefined08] [nvarchar](max) NULL,
	[UserDefined09] [nvarchar](max) NULL,
	[UserDefined10] [nvarchar](max) NULL,
	[ItemStatus] [nchar](2) NULL,
	[ItemReason] [nchar](10) NULL,
	[ExpectedLnDeliveryDate] [datetime] NULL,
	[ExpectedLnShipDate] [datetime] NULL,
	[ItemUPC] [nvarchar](50) NULL,
	[RetailPrice] [float] NULL,
	[PackingNotes] [nvarchar](max) NULL,
	[TrackingNumber] [nvarchar](50) NULL,
	[PurchaserItemCode] [nvarchar](100) NULL,
	[AssignedId] [nvarchar](20) NULL,
	[AssignedId2] [nvarchar](20) NULL,
	[ServiceLevel] [nvarchar](2) NULL,
	[Routing] [nvarchar](50) NULL,
	[TrackingNoText] [nvarchar](50) NULL,
	[DeliveryConfirmation] [nvarchar](50) NULL,
	[DeliveryText] [nvarchar](50) NULL,
	[VendorItemDescription] [nvarchar](255) NULL,
	[SalesEventName] [nvarchar](30) NULL,
	[SalesEventText] [nvarchar](80) NULL,
	[AllowanceType] [nvarchar](4) NULL,
	[Comments] [nvarchar](max) NULL,
	[AllowanceId] [nvarchar](4) NULL,
	[CustItemCode] [nvarchar](10) NULL,
 CONSTRAINT [PK_InfocusEdi850DetailRecord] PRIMARY KEY CLUSTERED 
(
	[DetailId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[InfocusEdi850DetailRecord]  WITH CHECK ADD  CONSTRAINT [FK_InfocusEdi850DetailRecord_InfocusEdi850HeaderRecord] FOREIGN KEY([HeaderId])
REFERENCES [dbo].[InfocusEdi850HeaderRecord] ([HeaderId])
GO
ALTER TABLE [dbo].[InfocusEdi850DetailRecord] CHECK CONSTRAINT [FK_InfocusEdi850DetailRecord_InfocusEdi850HeaderRecord]
GO
